### ISSUE TITLE
Can't run the parser

### ISSUE THREAD

**Issue by miguelgazela** [joweich/chat-miner#103]
Is there a specific Python version that should be used to run this parser? I can't run this, every time I solve an issue I have another one. I'm currently using Python 3.10.0.

**Comment by joweich** [comment]
@miguelgazela that's unfortunate. We have [tests for Python 3.8, 3.9, and 3.10](https://github.com/joweich/chat-miner/blob/main/.github/workflows/test.yml). The version pulled for 3.10 is 3.10.12.
What are the specific issues you are facing?

**Comment by joweich** [comment]
I see you're using Python 3.11. I will try to reproduce your issue.

**Comment by joweich** [comment]
@miguelgazela I was able to find the root cause in the typing we added in #98. For now, I removed all typing from the visualizations module as covering several python versions would add lots of boilerplate code.
This fixed the issue for you!

**Comment by miguelgazela** [comment]
Yep, it solved it! No more errors now, thanks! I can't seem to generate the graphs though. I tried running the following example:
`fig, ax = plt.subplots(2, 1, figsize=(9, 3))
ax[0] = vis.calendar_heatmap(df, year=2020, cmap='Oranges', ax=ax[0])`

but nothing happens. Do I need to call something else?

**Comment by BlueishTint** [comment]
Oops.
