### ISSUE TITLE
Add unit test for Command Line Interface

### ISSUE THREAD

**Issue by joweich** [joweich/chat-miner#113]
## Goal
The CLI does not yet have test coverage. This should be fixed within this issue. [This](https://stackoverflow.com/questions/52706049/how-to-test-a-python-cli-program-with-click-coverage-py-and-tox) stackoverflow post might be a hint on how to test CLIs in python.

## Jobs to be done
- [ ]  add unit test file `test_cli.py` to `test` dircetory

**Comment by nikhilgarg26** [comment]
hey @joweich i would like to take up this issue, can you please guide how to start with this issue it would be a great help

**Comment by joweich** [comment]
Hi @nikhilgarg26! Welcome on board! :rocket: 
Check out [this link](https://realpython.com/python-cli-testing/#pytest), it gives a great starting point on how to test clis with pytest.
