### ISSUE TITLE
Adding in ReadMe to use double backslashes or  raw string for FILEPATH

### ISSUE THREAD

**Issue by smty2018** [joweich/chat-miner#115]
While following the ReadMe instructions to use the package,
![image](https://github.com/joweich/chat-miner/assets/74114936/e09bfe32-6454-48eb-8618-c4c5fcdac732)

Directly put in unformatted file path("C:\Users\Sheetali\Downloads\text.txt"), which followed a syntax error due to  escape characters.
![image](https://github.com/joweich/chat-miner/assets/74114936/33417f77-c20e-4b7f-9100-e10070674d5e)

**I think this is a very common error users go through and can be avoided by adding a note in the ReadMe  for the FILE_PATH variable that  you can either use double backslashes or a raw string by prefixing the string with an 'r'.**

**Comment by joweich** [comment]
Closed via #116
