### ISSUE TITLE
Any Other language translated README

### ISSUE THREAD

**Issue by Durgesh4993** [joweich/chat-miner#117]
I am able create in 4 different languages
- Japanese
- Chinese
- German
- Hindi

**Comment by unsurp4ssed** [comment]
can do Russian

**Comment by joweich** [comment]
@Durgesh4993 @unsurp4ssed do you guys see the need for translations? How/where would you recommend linking the translations to not pollute the "main"-README with too many languages?

**Comment by unsurp4ssed** [comment]
I don't think that translations are _really necessary_. But we can make em, and it could help people, so why not :)
I believe that English, Chinese, Spanish, Russian, German, French, Japanese should be enough as these are the most spoken languages on the internet.

I'd make separate files, like README.ru.md, README.jp.md, and so on.
And after that we can simply place links to those translated readme's in the beginning/end of the "main"-readme.
