### ISSUE TITLE
Implement parser for Telegram chatfiles in HTML format

### ISSUE THREAD

**Issue by joweich** [joweich/chat-miner#12]
Implement a new parser enabling the processing of Telegram export files. Telegram files may be exported in both JSON and HTML format.
This issue targets the parsing of **HTML** files. The corresponding issue for JSON files is #11.
The logic should be aligned with the existing parser classes.

Please find more information about exporting Telegram chatlogs [here](https://telegram.org/blog/export-and-more).

**Comment by gajrajgchouhan** [comment]
I would like to work on this.
