### ISSUE TITLE
Author does not support having an emoji in it

### ISSUE THREAD

**Issue by alfonso46674** [joweich/chat-miner#33]
If i have a message that looks like this: 
```
DD-MM-YYY hh-mm - Alfonso 🤓: Lorem impsum
```
The function _get_message_author_ cannot interpret the emoji since the regex patterns do not take emojis into account. 
I've found an expression that matches any emoji (supposedly): https://www.regextester.com/106421
How I see this there are two options:
1. Create more regex rules to incorporate the use of emojis in the author.
2. Delete all emojis from the author except if it is made up only of emojis. 

I think the better solution is to delete all emojis from the author, it is easier to do and yields better data since there is no need to take emojis into account.
What do you think @joweich?

**Comment by joweich** [comment]
Yep, I would agree with you on option 2. Option 1 seems to pollute the code unnecessarily. 

Food for thought: What do you think of not stripping the emojis, but converting them to their encoding string and having this string as part of the author's name? This would circumvent the need for catching the _only-emoji-name_ case and the loss of information in general.

**Comment by joweich** [comment]
The wordcloud visual solely uses the message field of the dataframe, not the author. The author's name should therefore not appear there in any way

**Comment by alfonso46674** [comment]
Sounds good, I'll go ahead with your idea of converting the emojis to their encoding string. At least this way there will be no lost data since we are transforming the emojis instead of removing them

**Comment by alfonso46674** [comment]
FYI, It seems that https://github.com/joweich/chat-miner/pull/35 fixed the emoji not being recognized in the author. By checking what is between `timestamp_author_sep` (could be `-` or `]` ) and the character `:` instead of using regular expressions to get the author, now emojis are correctly processed. I'll add a couple of test lines to cover the problem. Should this issue be closed and a new one be opened as an enhancement for converting the emojis to Unicode values? Or should we stop here?

**Comment by joweich** [comment]
@alfonso46674 thank you for picking this up!
With #35, I attempted to simplify the message parsing while increasing the robustness of the author detection.
In a nutshell, we now only use a regex to detect if a line in the log starts with a date and therefore is a new message.
As you mentioned, the split between timestamp is done via either `' - '` or `'] '` (note the spaces). This approach seems to be stable for all messages formats we have seen yet.
Author and message body are always divided be `:`, so there's no need to overcomplicate things.
Please note that this comes with a slight decrease in performance.
