### ISSUE TITLE
Parser for MS Teams chats

### ISSUE THREAD

**Issue by FilippoULIVO** [joweich/chat-miner#55]
Feature proposal:
add a parser for teams chat.  here you can find documentation on how to download the chat https://support.microsoft.com/en-us/office/export-or-delete-your-microsoft-teams-free-data-1ed6ac68-5fb4-41be-9861-1a4127fecf68

let me know if I can help, maybe pointing me some ways

**Comment by joweich** [comment]
## Goal
Implement a new parser enabling the processing of MS Teams export files. The logic should be aligned with the existing parser classes.

## Jobs to be done
- [x] Do research on how to export MS Teams chats (see [this](https://support.microsoft.com/en-us/office/export-or-delete-your-microsoft-teams-free-data-1ed6ac68-5fb4-41be-9861-1a4127fecf68) link @FilippoULIVO provided)
- [ ] Create a new `class MSTeamsParser(Parser)`
- [ ] Create logic for _read_file_into_list() and _parse_message() like in the other parsers
- [ ] Add export tutorial to README
