### ISSUE TITLE
Facebook Messenger KeyError 'type'

### ISSUE THREAD

**Issue by Ponti17** [joweich/chat-miner#56]
When running the FacebookMessengerParser i get the following error

14.12.2022 14:20:56 INFO     
            Depending on the platform, the message format in chat logs might not be
            standardized accross devices/versions/localization and might change over
            time. Please report issues including your message format via GitHub.
            
14.12.2022 14:20:56 INFO     Initialized parser.
14.12.2022 14:20:56 INFO     Starting reading raw messages into memory...
14.12.2022 14:20:56 INFO     Finished reading 7567 raw messages into memory.
14.12.2022 14:20:56 INFO     Starting parsing raw messages into dataframe...
  0%|                                                                                                                                                    | 0/7567 [00:00<?, ?it/s]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [10], in <cell line: 4>()
      1 from chatminer.chatparsers import FacebookMessengerParser
      3 parser = FacebookMessengerParser('message_3.json')
----> 4 parser.parse_file_into_df()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:45, in Parser.parse_file_into_df(self)
     43 with logging_redirect_tqdm():
     44     for mess in tqdm(self.messages):
---> 45         parsed_mess = self._parse_message(mess)
     46         if parsed_mess:
     47             parsed_messages.append(parsed_mess)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:213, in FacebookMessengerParser._parse_message(self, mess)
    212 def _parse_message(self, mess):
--> 213     if mess["type"] == "Share":
    214         body = mess["share"]["link"]
    215     elif "sticker" in mess:

KeyError: 'type'

**Comment by haileymoore** [comment]
Hi! I had the same issue mentioned above with Facebook messenger. I tried the change mentioned in #57, which gave me a new error, `TypeError: unhashable type: 'dict'`. I then changed the new `else` line to `self._logger.warning("Skipped message without type-field: %s" % mess`, which made the script run, but it looks like nearly all messages in the file are skipped. It also finally ended with the following error lines:
```
Traceback (most recent call last):
  File "chatparse.py", line 3, in <module>
    parser.parse_file_into_df()
  File "/Users/Hailey/Library/Python/3.8/lib/python/site-packages/chatminer/chatparsers.py", line 50, in parse_file_into_df
    self._add_metadata()
  File "/Users/Hailey/Library/Python/3.8/lib/python/site-packages/chatminer/chatparsers.py", line 61, in _add_metadata
    self.df["weekday"] = self.df["datetime"].dt.day_name()
  File "/Users/Hailey/Library/Python/3.8/lib/python/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/Hailey/Library/Python/3.8/lib/python/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'datetime'
```

**Comment by Ponti17** [comment]
I get the exact same results as haileymoore. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 4>()
      1 from chatminer.chatparsers import FacebookMessengerParser
      3 parser = FacebookMessengerParser('message_1.json')
----> 4 parser.parse_file_into_df()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:46, in Parser.parse_file_into_df(self)
     44 with logging_redirect_tqdm():
     45     for mess in tqdm(self.messages):
---> 46         parsed_mess = self._parse_message(mess)
     47         if parsed_mess:
     48             parsed_messages.append(parsed_mess)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:233, in FacebookMessengerParser._parse_message(self, mess)
    231         body = mess["content"]
    232 else:
--> 233     self._logger.warning("Skipped message without type-field: %s", {mess})
    234     return None
    236 parsed_message = {
    237     "datetime": datetime.datetime.fromtimestamp(mess["timestamp_ms"] / 1000),
    238     "author": mess["sender_name"],
    239     "message": body,
    240 }

TypeError: unhashable type: 'dict'

**Comment by joweich** [comment]
@haileymoore @Ponti17 Thank you, the new error was a typo on my end and is now fixed with [cf4830c](https://github.com/joweich/chat-miner/pull/57/commits/cf4830ce50f7d20b7983e3be7a36d0bc1b9966fd).

> it looks like nearly all messages in the file are skipped

Seems like facebook might have changed the schema of their JSON exports then, as we had 3 people raising this in a very short time. 

Would you mind providing the schema of your JSON? Unfortunately, I'm not on facebook and can't export on my own.
I need to understand what adaption we need to make to the current logic here:

```
        if "type" in mess:
            if mess["type"] == "Share":
                body = mess["share"]["link"]
            elif "sticker" in mess:
                body = mess["sticker"]["uri"]
            else:
                body = mess["content"]
```

Also, if you want to fix this yourself, feel free to drop a PR, which I will then merge to the main branch 😊

**Comment by Ponti17** [comment]
I can't seem to figure it out. Messages in the JSON have this format

{
  "sender_name": "SENDER",
  "timestamp_ms": 1234567891234,
  "content": "MESSAGE"
},

**Comment by joweich** [comment]
@Ponti17 @haileymoore I received an export file throwing the error and was able to fix the issue. Please see #57, which is now merged on the main branch.
