### ISSUE TITLE
Pie chart for most used emoji

### ISSUE THREAD

**Issue by joweich** [joweich/chat-miner#61]
## Goal
Create a [pie chart](https://en.wikipedia.org/wiki/Pie_chart) to visualize the most used emoji. Matplotlib has an inbuild [pie chart](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.pie.html#matplotlib.axes.Axes.pie), which we should leverage here. Eventually, it should look like the pie chart [here](https://github.com/irfanchahyadi/Whatsapp-Chat-Analyzer/blob/master/assets/img4.png).

## Jobs to be done
- [ ] Leverage matplotlib's pie chart in chat-miner's [visualizations.py](https://github.com/joweich/chat-miner/blob/7990d239882de65c560b9ac41bdfaec30390196b/chatminer/visualizations.py) file as a new function `def piechart_emoji(df, ...)`
- [ ] Introduce parameter to limit pie chart to the n most frequent emoji defaulting to 10
- [ ] Introduce pandas logic to count emojis in parsed chat
- [ ] Add example to README

**Comment by MaNiLu2** [comment]
Hi, 

,if the problem is not solved yet I would like to try this. But since it's the first time I do something like that I can not promise anything :). LG

**Comment by joweich** [comment]
@MaNiLu2 sure! Feel free to give it a try, I would be happy to have you on board! 🙂
