### ISSUE TITLE
ValueError: Invalid date format (WhatsApp)

### ISSUE THREAD

**Issue by luqmansaleem99** [joweich/chat-miner#66]
My WhatsApp exported chat format is `8/21/21, 11:06 PM - NAME: MESSAGE`

I first tested Chat Miner on a chat that has only a few texts. It worked fine. But when I applied the same procedure to a chat that has a lot of texts, it gave me the following error:

> 05.01.2023 21:24:13 INFO     
>             Depending on the platform, the message format in chat logs might not be
>             standardized accross devices/versions/localization and might change over
>             time. Please report issues including your message format via GitHub.
>             
> 05.01.2023 21:24:13 INFO     Initialized parser.
> 05.01.2023 21:24:13 INFO     Starting reading raw messages into memory...
> 05.01.2023 21:24:13 INFO     Finished reading 40000 raw messages into memory.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In [16], line 3
>       1 from chatminer.chatparsers import WhatsAppParser
> ----> 3 parser = WhatsAppParser("wa.txt")
>       4 parser.parse_file_into_df()
> 
> File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:118, in WhatsAppParser.__init__(self, filepath)
>     116 def __init__(self, filepath):
>     117     super().__init__(filepath)
> --> 118     self._infer_datetime_format()
> 
> File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\chatminer\chatparsers.py:162, in WhatsAppParser._infer_datetime_format(self)
>     160     max_second = max(max_second, day_and_month[1])
>     161     if (max_first > 12) and (max_second > 12):
> --> 162         raise ValueError(f"Invalid date format: {line}")
>     164 if max_first > 12 and max_second <= 12:
>     165     self._logger.info("Inferred DMY format for date.")
> 
> ValueError: Invalid date format: 24.4.24

What could be the error? In my chat file "wa.txt", I tried to find a date "8/24/24" but there are no such date formats.

**Comment by luqmansaleem99** [comment]
Never mind. I found the error. There was a text that started from "24-4-24". Chat Miner thought it is a date. I removed this text and everything is working fine.

**Comment by joweich** [comment]
@luqmansaleem99 if you have a solution on how to catch this case in mind, feel free to drop a PR and contribute to this project! 🤗
