### ISSUE TITLE
Radarchart - unknown projection radar

### ISSUE THREAD

**Issue by vactomas** [joweich/chat-miner#69]
Hey,
I've been trying to use your library to create the graphs from my chat exports. Unfortunately, I have run into an issue with the radarchart.

The way the code executes creates a problem. First, it runs the matplotlib.subplots function with the subplot_kw argument. The radar projection is, however, defined in the vis.radar() function as a part of the radar_factory().

Therefore, I get ValueError: Unknown projection 'radar' because it is not yet defined, when the subplots function runs.

I am trying to build a [GUI](https://github.com/vactomas/chat-miner_GUI) for this library and this is the only thing, which I can't get to work.

How did you get yours to work?

**Comment by joweich** [comment]
Hi @vactomas!

> I am trying to build a [GUI](https://github.com/vactomas/chat-miner_GUI) for this library

Exciting, I will follow your progress closely! 

> Therefore, I get ValueError: Unknown projection 'radar' because it is not yet defined, when the subplots function runs.

That's true. The radar projection is created in the `radar_factory()` method via registering it at the local matplotlib (see [here](https://matplotlib.org/1.4.0/devel/add_new_projection.html)). If the method has never been run before, the error will be thrown if you define subplots explicitly. However, there are two workarounds I can imagine:

- Call `vis.radar_factory(7, frame="polygon") ` manually once to register the projection (this is the more robust solution)
- Call `vis.radar(parser.df, ax=None),` which will build the axis **after** registering the projection (you also only need to do this once)

Let me know if this works for you!

**Comment by vactomas** [comment]
Works great! I have already made a commit to my project. Thanks!

You might want to add this into the guide, so that others know.

**Comment by joweich** [comment]
@vactomas cool! Have you thought about adding a guide on how to set the GUI up into the README? Combined with a few screenshots, this will increase the adoption of your tool

**Comment by vactomas** [comment]
Yes, I have already added it today, along with the pre-release executable!

Thank you for building such wonderful library. I have already added Instagram to the list of GUI.
