### ISSUE TITLE
ValueError(f"Invalid date format: {line}")

### ISSUE THREAD

**Issue by Hugoo187** [joweich/chat-miner#72]
"11.01.2023 17:54:46 INFO     
            Depending on the platform, the message format in chat logs might not be
            standardized accross devices/versions/localization and might change over
            time. Please report issues including your message format via GitHub."
hi, as said in the error I should do report. 
"ValueError: Invalid date format: 20.15.21.15 h Stock Donnerstag  18.19 h Stock 19-20 Athletik" -> The programm reads it as a date, even if it is just a normal text (message).

**Comment by joweich** [comment]
@Hugoo187 thank you for raising this! I was able to identify the issue and fixed it with #76
