### ISSUE TITLE
TypeError: isinstance is missing 1 argument in the chatparser

### ISSUE THREAD

**Issue by vactomas** [joweich/chat-miner#84]
Hi,

I just wanted to play around with the chat-miner, but I ran into the following error. I have the latest version of the module, and I tried to just copy the code in the README.md, but no luck. Could you please take a look at it?

```
File "...\chatminer\chatparsers.py", line 284, in <lambda>
    lambda m: m["text"] if isinstance(m) is dict else m,
                           ^^^^^^^^^^^^^
TypeError: isinstance expected 2 arguments, got 1
```

EDIT: I am using the TelegramJsonParser

**Comment by joweich** [comment]
@vactomas thank you for raising this! The fix will be part of the very next release
