### ISSUE TITLE
Single graph instead of two

### ISSUE THREAD

**Issue by amar3lo** [joweich/chat-miner#94]
it is possible to generate a single graph  only? 
i got only  this year of data

**Comment by joweich** [comment]
@amar3lo yes, you can create all the graphs independent from each other.
The matplotlib syntax changes to this (example for calendar heatmap):
```
fig, ax = plt.subplots(1, 1, figsize=(9, 3))
ax = vis.calendar_heatmap(df, year=2020, cmap='Oranges', ax=ax)
```

**Comment by amar3lo** [comment]
works like a charm!!! thank you!!
